### ISSUE TITLE
Sync Keeps Stalling

### ISSUE THREAD

**Issue by reganhimself** [wellenreiter01/feathercoin-wallet-2#13]
I have recently imported keys from a old broken phone however i cannot get the app to resync so that i can transfer my coins out. 

Is there anything i can do to get this to work? Do you know what is causing it to fall over?

**Comment by wellenreiter01** [comment]
The Android wallet is not maintained anymore and can't sync due to protocol changes in the feathercoin core.
http://forum.feathercoin.com/topic/9913/feathercoin-wallet-2-for-android-is-obsolete

use this process to recover and transfer your coins to another wallet:
http://forum.feathercoin.com/topic/9216/guide-how-to-recover-private-keys-from-the-android-featherwallet
